# Generated by Django 5.0.6 on 2024-07-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.TextField(default='user', max_length=255),
        ),
    ]
