# Generated by Django 5.0.6 on 2024-08-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('choices', models.JSONField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('number_of_points', models.IntegerField()),
            ],
        ),
    ]
