# Generated by Django 5.0.6 on 2024-11-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Express', 'Express'), ('Business', 'Business')], default=None, max_length=10, null=True),
        ),
    ]
