# Generated by Django 5.0.6 on 2024-11-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_user_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
