# Generated by Django 5.0.6 on 2024-12-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_courserequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='author',
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
    ]
