# Generated by Django 5.0.6 on 2024-12-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_course_author_remove_course_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=2),
        ),
    ]
