# Generated by Django 5.0.6 on 2024-12-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_testresult_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='block',
            field=models.IntegerField(choices=[(1, 'Block 1'), (2, 'Block 2'), (3, 'Block 3')], default=1),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_in_the_blank', 'Fill in the Blank'), ('true_false', 'True/False')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
