# Generated by Django 5.0.6 on 2024-12-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_lesson_block_alter_exercise_exercise_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='choices',
            field=models.JSONField(default=list),
        ),
    ]
