# Generated by Django 5.0.6 on 2024-12-11 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_lesson_content_alter_lessontheory_audio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
    ]
