# Generated by Django 5.0.6 on 2024-12-11 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_lesson_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exerciseresult',
            unique_together={('user', 'lesson', 'exercise')},
        ),
        migrations.AlterField(
            model_name='exerciseresult',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exerciseresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exerciseresult',
            name='user_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='exerciseresult',
            name='created_at',
        ),
    ]
