# Generated by Django 5.0.6 on 2024-12-11 02:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_exerciseresult_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
